export const ROUTES = {
  home: '/',
  upload: '/upload',
  preview: '/preview',
  converting: '/converting',
  pricing: '/pricing',
  guide: '/guide',
  support: '/support',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: (token: string) => `/reset-password/${token}`,

  dashboard: '/dashboard',
  conversions: '/conversions',
  conversion: (id: string | number) => `/conversions/${id}`,
  conversionDownload: (id: string | number) => `/conversions/${id}/download`,
  wallet: '/wallet',
  walletTransactions: '/wallet/transactions',
  payments: '/payments',
  paymentDetail: (id: string | number) => `/payments/${id}`,
  tickets: '/tickets',
  ticketDetail: (id: string | number) => `/tickets/${id}`,
  profile: '/profile',
  history: '/history',
  transactions: '/transactions',

  admin: '/admin',
  adminUsers: '/admin/users',
  adminUserDetail: (id: string | number) => `/admin/users/${id}`,
  adminCoinPackages: '/admin/coin-packages',
  adminPayments: '/admin/payments',
  adminConversions: '/admin/conversions',
  adminCoinTransactions: '/admin/coin-transactions',
  adminTickets: '/admin/tickets',
  adminSupportUsers: '/admin/support-users',
  adminSettings: '/admin/settings',
  adminAuditLogs: '/admin/audit-logs',

  supportDashboard: '/support-dashboard',
} as const;
