package com.pdfconverter.common.exception;

import org.springframework.http.HttpStatus;

/**
 * Mã lỗi nghiệp vụ. Tham khảo bảng error code trong done/backend/api_spec.md.
 */
public enum ErrorCode {
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    ACCOUNT_LOCKED(HttpStatus.FORBIDDEN),
    ACCESS_DENIED(HttpStatus.FORBIDDEN),
    NOT_FOUND(HttpStatus.NOT_FOUND),
    EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT),
    INVALID_FILE_TYPE(HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    FILE_TOO_LARGE(HttpStatus.PAYLOAD_TOO_LARGE),
    PDF_READ_FAILED(HttpStatus.UNPROCESSABLE_ENTITY),
    FREE_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS),
    FREE_FILE_TOO_LARGE(HttpStatus.UNPROCESSABLE_ENTITY),
    FREE_PAGE_TOO_MANY(HttpStatus.UNPROCESSABLE_ENTITY),
    INSUFFICIENT_COIN(HttpStatus.UNPROCESSABLE_ENTITY),
    QUEUE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    UPLOAD_TOKEN_INVALID(HttpStatus.BAD_REQUEST),
    UPLOAD_TOKEN_EXPIRED(HttpStatus.BAD_REQUEST),
    AUTH_REQUIRED_FOR_PREMIUM(HttpStatus.UNAUTHORIZED),
    CONVERSION_NOT_SUCCESS(HttpStatus.UNPROCESSABLE_ENTITY),
    FILE_EXPIRED(HttpStatus.GONE),
    FILE_DELETED(HttpStatus.GONE),
    UPLOAD_STORAGE_FAILED(HttpStatus.SERVICE_UNAVAILABLE),
    WORKER_TOKEN_INVALID(HttpStatus.UNAUTHORIZED),
    CONVERSION_ALREADY_PROCESSED(HttpStatus.CONFLICT),
    IDEMPOTENCY_KEY_REUSE(HttpStatus.CONFLICT),
    REFRESH_TOKEN_INVALID(HttpStatus.UNAUTHORIZED),
    REFRESH_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED),
    RESET_TOKEN_INVALID(HttpStatus.BAD_REQUEST),
    RESET_TOKEN_EXPIRED(HttpStatus.BAD_REQUEST),
    PASSWORD_MISMATCH(HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD(HttpStatus.BAD_REQUEST);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus status() {
        return status;
    }
}